import { check, choice, field, result, row } from "../shared.js";

const base = { organization: "Northline Distribution", kind: "Client", agreement: true, contact: "Jordan Lee", email: "jordan@example.test", taxDocument: true, insurance: false, model: "SME" };
export default {
  id: "onboarding-operations", title: "Client & Vendor Onboarding", shortTitle: "Onboarding", category: "Business operations", number: "05", accent: "#d7c89b",
  headline: "Start the relationship with everything in place.", description: "Turn an approved engagement into a checked document pack, a workspace, and assigned handoff tasks. Missing items stay visible.",
  inputTitle: "Engagement checklist", outputTitle: "Onboarding plan", sourceLabel: "Fictional engagement · completeness rules v1",
  fields: [field("organization", "Organization"), choice("kind", "Relationship", ["Client", "Vendor"]), field("agreement", "Signed agreement received", "checkbox"), field("contact", "Primary contact"), field("email", "Contact email", "email"), field("taxDocument", "Tax document received", "checkbox"), field("insurance", "Vendor insurance received", "checkbox")],
  scenarios: [{ id: "standard", label: "Ready to onboard", note: "A client engagement has the required documents and contact.", input: base }, { id: "exception", label: "Missing documents", note: "A vendor cannot be activated until its required documents arrive.", input: { ...base, organization: "Lakeside Components", kind: "Vendor", agreement: false, insurance: false } }, { id: "enterprise", label: "Enterprise vendor", note: "A complete vendor pack needs operations and procurement review.", input: { ...base, organization: "Cedar Packaging", kind: "Vendor", insurance: true, model: "Enterprise" } }],
  prepare(input) {
    const vendor = input.kind === "Vendor";
    const checks = [check("Organization", Boolean(input.organization.trim()), "Enter the organization name."), check("Agreement", input.agreement, "Collect the signed agreement."), check("Named contact", Boolean(input.contact.trim()) && /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(input.email), "Provide a named contact and valid email."), check("Tax document", input.taxDocument, "Collect the required tax document."), check("Vendor insurance", !vendor || input.insurance, "Collect vendor insurance before activation.")];
    const missing = checks.filter((item) => !item.pass).map((item) => item.detail);
    return result({ title: `${input.organization || "Organization required"} / ${input.kind}`, summary: missing.length ? `${missing.length} requirements need attention before activation.` : "The required checklist is complete and ready for review.",
      rows: [row("Relationship", input.kind, "Engagement record"), row("Accountable owner", vendor ? "Procurement" : "Customer success", "Routing rules v1"), row("Document checks", `${checks.filter((c) => c.pass).length} / ${checks.length} complete`, "Operator-attested document receipt"), row("Contact", input.email || "Missing", "Engagement record")], checks,
      role: vendor ? "Procurement lead" : "Customer success lead", action: `Activate ${input.kind.toLowerCase()} workspace`,
      body: missing.length ? `DOCUMENT REQUEST DRAFT\nHello ${input.contact || "team"},\n\nTo complete onboarding for ${input.organization}, please provide:\n${missing.map((m) => `- ${m}`).join("\n")}\n\nThis is a draft only; no message has been sent.` : `ONBOARDING HANDOFF\nOrganization: ${input.organization}\nType: ${input.kind}\nContact: ${input.contact} (${input.email})\n\nCreate the ${vendor ? "vendor" : "client"} workspace, assign ${vendor ? "procurement" : "customer success"}, and schedule a kickoff task.\n\nDocument receipt is attested in this demo. Authenticity, legal sufficiency, and compliance are not evaluated.`,
      records: [{ system: "CRM sandbox", operation: `Activate ${input.kind.toLowerCase()} record`, record: input.organization }, { system: "Workspace sandbox", operation: "Create checklist & kickoff task", record: input.organization }], metrics: [{ label: "Relationship", value: input.kind }, { label: "Checklist complete", value: `${checks.filter((c) => c.pass).length}/${checks.length}` }, { label: "Missing items", value: String(missing.length) }],
    });
  },
};
